######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 2 15:46:46 2014
######################################################################

TEMPLATE = app
QT += widgets
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
