######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 10 11:30:05 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
