######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 3 11:28:43 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
